### PR TITLE
adding support for video upload and example.config file fixed #183

### LINKED ISSUE #183: Unable to upload MP4 media
So the REST API now [supports the upload of video](https://blog.twitter.com/2015/rest-api-now-supports-native-video-upload). Cool stuff! [Guidelines here.](https://dev.twitter.com/rest/public/uploading-media)

I've managed to get an authenticate-able POST request together, but I get the following error:

```
{ [Error: Unknown Twitter API Error]
  message: 'Unknown Twitter API Error',
  statusCode: 400,
  twitterReply: '{"request":"\\/1.1\\/media\\/upload.json","error":"media type unrecognized."}',
  code: null,
  allErrors: [] }
```

I triple-checked that the .mp4 itself is fine, in size, dimension, FPS, and audio (side note: the docs don't say it yet, but they only support mono & stereo — no 5.1 sound).

From what I can tell, it looks like the 'Content-Type' in the POST request might not be set correctly. Unfortunately, this is the limit of my understanding. Is this an issue with the lib, or something that I'm doing wrong?

### PR DESCRIPTION
**Pull request by gabrielstuff**
This update allow to use the `/upload` api and the chunk documentation to post video file.
Please find here : https://googledrive.com/host/0B83FWeLjxMvhd0dSb1ltckhjRHc a video file which works fine.

Thanks

### CODE REVIEW

**Comment by gabrielstuff** [comment]
Not yet ready to merge. The example does not show a full support for video file over 5Mo.
Working on it. 
Thanks

**Comment by gabrielstuff** [comment]
Ok now it is ready @ttezel. I think it would be helpful for anyone who tried to push video on twitter. Thanks for the amazing work so far !

**Comment by ttezel** [comment]
Hi @gabrielstuff! I've added twit.postMediaChunked() to make this easy, and you can use the INIT/APPEND/FINALIZE commands manually too, check out the readme for info on doing this via `twit.postMediaChunked()` and manually :)

**Comment by ttezel** [comment]
Usage is like:
```
var filePath = '/absolute/path/to/file.mp4'
T.postMediaChunked({ file_path: filePath }, function (err, data, response) {
  console.log(data)
})
```

**Comment by gabrielstuff** [comment]
This looks perfect. Going to try later this weekend. Thanks !

**Pull request closed without merging**
