### PR TITLE
Curator

### PR DESCRIPTION
**Pull request by super-ienien**
Here is an implementation of the curator API

### CODE REVIEW

**Comment by gabrielstuff** [comment]
Wow great ! This is a must have ! Thanks @super-ienien for implementing this.

**Comment by super-ienien** [comment]
Yes it can be usefull, but only if you have access to the curator API that is restricted to TV Broadcasters. I wrote this for a project with a TV production company wich have this access. It worked fine.

**Comment by talha-asad** [comment]
Can you rebase this with the current master?

**Comment by super-ienien** [comment]
done. I didn't test it deeply since the rebase but it's seems to works fine

**Comment by andypiper** [comment]
The Curator API no longer exists.

**Pull request closed without merging**
